//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialCrm.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanlar boş bırakılamaz!.
        /// </summary>
        internal static string alanlarbos {
            get {
                return ResourceManager.GetString("alanlarbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string bilgi {
            get {
                return ResourceManager.GetString("bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Hareketleri.
        /// </summary>
        internal static string btnBankProcessForm {
            get {
                return ResourceManager.GetString("btnBankProcessForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankalar.
        /// </summary>
        internal static string btnBanksForm {
            get {
                return ResourceManager.GetString("btnBanksForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturalar.
        /// </summary>
        internal static string btnBillingForm {
            get {
                return ResourceManager.GetString("btnBillingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        internal static string btnCategoryForm {
            get {
                return ResourceManager.GetString("btnCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string btnSettingsForm {
            get {
                return ResourceManager.GetString("btnSettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giderler.
        /// </summary>
        internal static string btnSpendingForm {
            get {
                return ResourceManager.GetString("btnSpendingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster/Gizle.
        /// </summary>
        internal static string cmbShowHide1 {
            get {
                return ResourceManager.GetString("cmbShowHide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde sisteme eklendi..
        /// </summary>
        internal static string eklendi {
            get {
                return ResourceManager.GetString("eklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde giriş yaptınız..
        /// </summary>
        internal static string girisbasarili {
            get {
                return ResourceManager.GetString("girisbasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı kullanıcı adı veya parola!.
        /// </summary>
        internal static string girisbasarisiz {
            get {
                return ResourceManager.GetString("girisbasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 5 Banka Hareketi.
        /// </summary>
        internal static string grpSon5BankaHareketi {
            get {
                return ResourceManager.GetString("grpSon5BankaHareketi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen güncellenecek bir değer seçiniz..
        /// </summary>
        internal static string guncellemedegerbos {
            get {
                return ResourceManager.GetString("guncellemedegerbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde sistemde güncellendi..
        /// </summary>
        internal static string guncellendi {
            get {
                return ResourceManager.GetString("guncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata!.
        /// </summary>
        internal static string hata {
            get {
                return ResourceManager.GetString("hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz!.
        /// </summary>
        internal static string hosgeldiniz {
            get {
                return ResourceManager.GetString("hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        internal static string lblaciklama {
            get {
                return ResourceManager.GetString("lblaciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar Formu.
        /// </summary>
        internal static string lblayarlarformu {
            get {
                return ResourceManager.GetString("lblayarlarformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka:.
        /// </summary>
        internal static string lblbanka {
            get {
                return ResourceManager.GetString("lblbanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Formu.
        /// </summary>
        internal static string lblBankaFormu {
            get {
                return ResourceManager.GetString("lblBankaFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Hareketleri Formu.
        /// </summary>
        internal static string lblbankahareketleriformu {
            get {
                return ResourceManager.GetString("lblbankahareketleriformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Başlığı.
        /// </summary>
        internal static string lblBillTitle {
            get {
                return ResourceManager.GetString("lblBillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı:.
        /// </summary>
        internal static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finansal CRM Projesi.
        /// </summary>
        internal static string lblcrm {
            get {
                return ResourceManager.GetString("lblcrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard / Genel Bakış Formu.
        /// </summary>
        internal static string lbldashboardformu {
            get {
                return ResourceManager.GetString("lbldashboardformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık:.
        /// </summary>
        internal static string lblfaturabaslik {
            get {
                return ResourceManager.GetString("lblfaturabaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Formu.
        /// </summary>
        internal static string lblFaturaFormu {
            get {
                return ResourceManager.GetString("lblFaturaFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar:.
        /// </summary>
        internal static string lblfaturamiktar {
            get {
                return ResourceManager.GetString("lblfaturamiktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periyot:.
        /// </summary>
        internal static string lblfaturaperiyot {
            get {
                return ResourceManager.GetString("lblfaturaperiyot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finansal CRM Projesi.
        /// </summary>
        internal static string lblfinancialcrmproje {
            get {
                return ResourceManager.GetString("lblfinancialcrmproje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Son Havale.
        /// </summary>
        internal static string lblgelensonhavale {
            get {
                return ResourceManager.GetString("lblgelensonhavale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Adı:.
        /// </summary>
        internal static string lblgideradi {
            get {
                return ResourceManager.GetString("lblgideradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giderler Formu.
        /// </summary>
        internal static string lblGiderlerFormu {
            get {
                return ResourceManager.GetString("lblGiderlerFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankalar ve banka hesaplarındaki para miktarlarına aşağıdaki grafikten ulaşabilirsiniz..
        /// </summary>
        internal static string lblgrafikmetin1 {
            get {
                return ResourceManager.GetString("lblgrafikmetin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenen ve ödenmesi gereken fatura tutarlarına aşağıdaki grafikten ulaşabilirsiniz..
        /// </summary>
        internal static string lblgrafikmetin2 {
            get {
                return ResourceManager.GetString("lblgrafikmetin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori:.
        /// </summary>
        internal static string lblkategori {
            get {
                return ResourceManager.GetString("lblkategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Formu.
        /// </summary>
        internal static string lblkategoriformu {
            get {
                return ResourceManager.GetString("lblkategoriformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string lblkullaniciadi {
            get {
                return ResourceManager.GetString("lblkullaniciadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar:.
        /// </summary>
        internal static string lblmiktar {
            get {
                return ResourceManager.GetString("lblmiktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola:.
        /// </summary>
        internal static string lblparola {
            get {
                return ResourceManager.GetString("lblparola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        internal static string lbltarih {
            get {
                return ResourceManager.GetString("lbltarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Bakiyem.
        /// </summary>
        internal static string lbltoplambakiyem {
            get {
                return ResourceManager.GetString("lbltoplambakiyem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür:.
        /// </summary>
        internal static string lbltur {
            get {
                return ResourceManager.GetString("lbltur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programdan çıkmak istiyor musunuz?.
        /// </summary>
        internal static string programdancikma {
            get {
                return ResourceManager.GetString("programdancikma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNGİLİZCE.
        /// </summary>
        internal static string rdbEnglish {
            get {
                return ResourceManager.GetString("rdbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜRKÇE.
        /// </summary>
        internal static string rdbTurkish {
            get {
                return ResourceManager.GetString("rdbTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen değeri güncellemek istiyor musunuz?.
        /// </summary>
        internal static string secilendegerguncelle {
            get {
                return ResourceManager.GetString("secilendegerguncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen değeri silmek istiyor musunuz?.
        /// </summary>
        internal static string secilendegersil {
            get {
                return ResourceManager.GetString("secilendegersil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde sistemden silindi..
        /// </summary>
        internal static string silindi {
            get {
                return ResourceManager.GetString("silindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silinecek bir değer seçiniz..
        /// </summary>
        internal static string silmedegerbos {
            get {
                return ResourceManager.GetString("silmedegerbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı!.
        /// </summary>
        internal static string uyari {
            get {
                return ResourceManager.GetString("uyari", resourceCulture);
            }
        }
    }
}
